import "AutomationConditions.idl";
import "AutomationEnums.idl";

namespace uia
{
    [default_interface]
    runtimeclass AutomationCacheRequest
    {
        //AutomationElementMode{ get; set; };
        AutomationCondition TreeFilter{ get; set; };
        AutomationTreeScope Scope{ get; set; };

        //void AddPattern();
        //void AddProperty();
        AutomationCacheRequest Clone();
    }
}
