namespace uia
{
    enum AutomationLiveSetting {
        Off,
        Polite,
        Assertive
    };

    enum PropertyConditionOptions {
        None,
        IgnoreCase
    };

    enum AutomationTreeScope {
        None,
        Element,
        Children,
        Descendants,
        Parent,
        Ancestors,
        Subtree
    };

    enum ElementMode {
        None, 
        Full
    };

    enum Orientation {
        None,
        Horizontal,
        Vertical
    };
}