import "AutomationConditions.idl";
import "AutomationEnums.idl";
import "AutomationPattern.idl";
import "AutomationProperty.idl";

namespace uia
{
    [default_interface]
    runtimeclass AutomationCacheRequest
    {
        ElementMode Mode{ get; set; };
        AutomationCondition TreeFilter{ get; set; };
        AutomationTreeScope Scope{ get; set; };

        void AddPattern(AutomationPattern pattern);
        void AddProperty(AutomationProperty property);
        AutomationCacheRequest Clone();
    }
}
