namespace uia
{
    [default_interface]
    runtimeclass AutomationProperty
    {
        Int32 Id{ get; };

        static AutomationProperty LookupById(Int32 propertyId);

        static AutomationProperty AcceleratorKey{ get; };
        static AutomationProperty AccessKey{ get; };
        static AutomationProperty AnnotationObjects{ get; };
        static AutomationProperty AnnotationTypes{ get; };
        static AutomationProperty AriaProperties{ get; };
        static AutomationProperty AriaRole{ get; };
        static AutomationProperty AutomationId{ get; };
        static AutomationProperty BoundingRectangle{ get; };
        static AutomationProperty CenterPoint{ get; };
        static AutomationProperty ClassName{ get; };
        static AutomationProperty ClickablePoint{ get; };
        static AutomationProperty ControllerFor{ get; };
        static AutomationProperty ControlType{ get; };
        static AutomationProperty Culture{ get; };
        static AutomationProperty DescribedBy{ get; };
        static AutomationProperty FillColor{ get; };
        static AutomationProperty FillType{ get; };
        static AutomationProperty FlowsFrom{ get; };
        static AutomationProperty FlowsTo{ get; };
        static AutomationProperty FrameworkId{ get; };
        static AutomationProperty FullDescription{ get; };
        static AutomationProperty HasKeyboardFocus{ get; };
        static AutomationProperty HeadingLevel{ get; };
        static AutomationProperty HelpText{ get; };
        static AutomationProperty IsContentElement{ get; };
        static AutomationProperty IsControlElement{ get; };
        static AutomationProperty IsDataValidForForm{ get; };
        static AutomationProperty IsDialog{ get; };
        static AutomationProperty IsEnabled{ get; };
        static AutomationProperty IsKeyboardFocusable{ get; };
        static AutomationProperty IsOffscreen{ get; };
        static AutomationProperty IsPassword{ get; };
        static AutomationProperty IsPeripheral{ get; };
        static AutomationProperty IsRequiredForForm{ get; };
        static AutomationProperty ItemStatus{ get; };
        static AutomationProperty ItemType{ get; };
        static AutomationProperty LabeledBy{ get; };
        static AutomationProperty LandmarkType{ get; };
        static AutomationProperty Level{ get; };
        static AutomationProperty LiveSetting{ get; };
        static AutomationProperty LocalizedControlType{ get; };
        static AutomationProperty LocalizedLandmarkType{ get; };
        static AutomationProperty Name{ get; };
        static AutomationProperty NativeWindowHandle{ get; };
        static AutomationProperty OptimizeForVisualContent{ get; };
        static AutomationProperty Orientation{ get; };
        static AutomationProperty OutlineColor{ get; };
        static AutomationProperty OutlineThickness{ get; };
        static AutomationProperty PositionInSet{ get; };
        static AutomationProperty ProcessId{ get; };
        static AutomationProperty ProviderDescription{ get; };
        static AutomationProperty Rotation{ get; };
        static AutomationProperty RuntimeId{ get; };
        static AutomationProperty Size{ get; };
        static AutomationProperty SizeOfSet{ get; };
        static AutomationProperty VisualEffects{ get; };
    }
}